import {useCallback,useEffect,useMemo,useRef,useState,createContext,useContext,type FormEvent,type ReactNode,type MouseEvent} from 'react';
import {Link,NavLink,Route,Routes,useLocation,useNavigate,useParams} from 'react-router-dom';
import {ArrowLeft,ArrowRight,BadgePercent,Box,Check,ChevronRight,CircleHelp,ClipboardList,Crown,Gift,Heart,Home as HomeIcon,MapPin,Minus,Package,Plus,Search as SearchIcon,ShieldCheck,ShoppingBag,ShoppingCart,Sparkles,Star,Trash2,Truck,UserRound,X,Zap,Settings2,Ticket,LogOut,ChevronDown,Copy,Clock3,Flame,Layers3,UploadCloud} from 'lucide-react';
import {api,json} from './api';
import {type Product,type Me,type Cart,type Banner,type Category,type Order,type Coupon,type Variant,type Brand,price,statusTitle} from './types';

declare global {interface Window {Telegram?:{WebApp?:{initData:string;ready:()=>void;expand:()=>void;close:()=>void;HapticFeedback?:{impactOccurred:(v:string)=>void};setHeaderColor?:(s:string)=>void}}}}
const UserContext=createContext<{me:Me|null;brand:string;bonusPercent:number;checkoutEnabled:boolean;refreshMe:()=>Promise<void>;cartCount:number;refreshCart:()=>Promise<void>;notify:(s:string,type?:'error'|'ok')=>void}>({me:null,brand:'VAPORIA DISTRO',bonusPercent:5,checkoutEnabled:false,refreshMe:async()=>{},cartCount:0,refreshCart:async()=>{},notify:()=>{}});
const useStore=()=>useContext(UserContext);
function useFetch<T>(endpoint:string,deps:unknown[]=[]){const [data,setData]=useState<T|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await api<T>(endpoint));}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[endpoint]);
  useEffect(()=>{void load();},[load,...deps]);return {data,setData,loading,error,reload:load};}
const notifyError=(err:unknown,notify:(s:string,t?:'error'|'ok')=>void)=>notify(err instanceof Error?err.message:'Сталася помилка','error');
const moneyInput=(p:number)=>String(p/100);
const kop=(s:string|number)=>Math.max(0,Math.round(Number(s||0)*100));

function Shell({children}:{children:ReactNode}){
 const loc=useLocation(),{brand,cartCount,me}=useStore();const navigate=useNavigate();
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[loc.pathname]);
 const tabs=[{path:'/',label:'Головна',icon:HomeIcon},{path:'/catalog',label:'Каталог',icon:Layers3},{path:'/search',label:'Пошук',icon:SearchIcon},{path:'/cart',label:'Кошик',icon:ShoppingCart},{path:'/profile',label:'Профіль',icon:UserRound}];
 return <div className="app-shell"><div className="ambient-glow"/>
 <header className="app-header"><button className="icon-btn back-btn" aria-label="Назад" onClick={()=>loc.pathname==='/'?window.Telegram?.WebApp?.close():navigate(-1)}><ArrowLeft size={21}/></button><Link to="/" className="header-brand"><span className="small-crown"><Crown size={13}/></span>{brand}</Link><div className="header-tools"><Link to="/favorites" aria-label="Обране"><Heart size={20}/></Link><Link to="/cart" aria-label="Кошик"><ShoppingBag size={19}/>{cartCount>0&&<i className="badge-count">{cartCount}</i>}</Link></div></header>
 <div className="app-body">{children}</div>
 <nav className="bottom-nav" aria-label="Головне меню">{tabs.map(t=><NavLink key={t.path} to={t.path} end={t.path==='/'} className={({isActive})=>`nav-tab ${isActive?'active':''}`}><span className="nav-icon"><t.icon size={21} strokeWidth={1.8}/>{t.path==='/cart'&&cartCount>0&&<span className="mini-dot">{cartCount}</span>}</span><span>{t.label}</span></NavLink>)}</nav>
 <div className="safe-footer"/></div>;
}
function PageTitle({children,subtitle}:{children:ReactNode;subtitle?:string}){return <div className="page-title"><h1>{children}</h1>{subtitle&&<p>{subtitle}</p>}</div>;}
function Loading(){return <div className="loading-block"><span className="spin"/> Завантаження...</div>;}
function Empty({icon=Package,title,subtitle,link,linkText}:{icon?:typeof Package;title:string;subtitle?:string;link?:string;linkText?:string}){const Icon=icon;return <div className="empty-state"><div className="empty-icon"><Icon size={34}/></div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}{link&&<Link to={link} className="button primary">{linkText||'До каталогу'} <ArrowRight size={16}/></Link>}</div>;}
function Art({product,className='',size='normal'}:{product?:Partial<Product>|{name:string;brand?:string;image_url?:string;slug?:string};className?:string;size?:string}){
 const [imageError,setImageError]=useState(false);
 useEffect(()=>setImageError(false),[product?.image_url]);
 const name=(product?.name||'VAPORIA').toUpperCase(),brand=product?.brand || (name.includes('VAPORESSO')?'VAPORESSO':name.split(' ')[0]);
 const hue=name.includes('HYPE')?'violet':name.includes('CHASER')?'lime':name.includes('VAPORESSO')?'cyan':name.includes('INBOTTLE')?'purple':'blue';
 return <div className={`product-art ${hue} ${size} ${className}`}>
 <div className="art-haze"/><div className="art-rays"/>
 {product?.image_url&&!imageError?<img className="real-product-img" src={product.image_url} alt={product.name||'Товар'} loading="lazy" onError={()=>setImageError(true)}/>:
 <div className="product-illustration"><div className="bottle-cap"/><div className="bottle-neck"/><div className="bottle-body"><span className="bottle-logo">{brand.slice(0,11)}</span><span className="bottle-name">{name.split(' ').slice(0,2).join(' ').slice(0,15)}</span><span className="bottle-footer">PREMIUM COLLECTION</span></div><div className="art-shadow"/></div>}
 <div className="art-spark">✦</div></div>;
}
function ProductCard({product,onChanged}:{product:Product;onChanged?:()=>void}){
 const {notify,refreshCart}=useStore(),[fav,setFav]=useState(false),[adding,setAdding]=useState(false);
 const add=async(e:MouseEvent)=>{e.preventDefault();e.stopPropagation();const v=product.variants.find(v=>v.is_active&&v.stock>0);if(!v)return notify('Товару немає в наявності','error');setAdding(true);try{await api('/cart',json('POST',{variant_id:v.id,quantity:1}));await refreshCart();notify('Додано до кошика');}catch(err){notifyError(err,notify);}finally{setAdding(false);}};
 const toggle=async(e:MouseEvent)=>{e.preventDefault();e.stopPropagation();try{const r=await api<{favorite:boolean}>(`/me/favorites/${product.id}`,json('POST'));setFav(r.favorite);onChanged?.();notify(r.favorite?'Додано в обране':'Прибрано з обраного');}catch(err){notifyError(err,notify);}};
 return <Link to={`/product/${product.slug}`} className="product-card"><div className="product-visual"><Art product={product}/>{product.badge&&<span className="product-label">{product.badge}</span>}<button className={`favorite-float ${fav?'is-fav':''}`} onClick={toggle} aria-label="В обране"><Heart size={17} fill={fav?'currentColor':'none'}/></button></div><div className="product-card-info"><span className="product-brand">{product.brand||'VAPORIA SELECTION'}</span><h3>{product.name}</h3><p>{product.subtitle}</p><div className="product-price"><div><strong>{price(product.base_price)}</strong>{product.compare_at_price&&<del>{price(product.compare_at_price)}</del>}</div><button onClick={add} disabled={adding||!product.variants.some(v=>v.stock>0)} aria-label="Додати в кошик"><ShoppingCart size={18}/></button></div></div></Link>;
}
const PRIMARY_CATEGORY_SLUGS=['pod-systemy','ridyny','kartrydzhi'];
function HeroCarousel({banners}:{banners:Banner[]}){
 const [active,setActive]=useState(0),touchX=useRef<number|null>(null);
 useEffect(()=>{setActive(i=>Math.min(i,Math.max(0,banners.length-1)));},[banners.length]);
 useEffect(()=>{if(banners.length<2)return;const timer=window.setInterval(()=>setActive(i=>(i+1)%banners.length),6500);return ()=>window.clearInterval(timer);},[banners.length]);
 if(!banners.length)return <Link to="/catalog" className="hero-carousel hero-fallback"><img src="/banners/main.webp" alt="VAPORIA DISTRO — головний банер"/></Link>;
 const change=(direction:number)=>setActive(i=>(i+direction+banners.length)%banners.length);
 const current=banners[active];
 return <section className="hero-carousel" aria-label="Акції та інформація магазину" onTouchStart={e=>{touchX.current=e.touches[0]?.clientX??null;}} onTouchEnd={e=>{if(touchX.current===null)return;const distance=e.changedTouches[0].clientX-touchX.current;if(Math.abs(distance)>38)change(distance>0?-1:1);touchX.current=null;}}>
 <Link key={current.id} className="carousel-banner-link" to={current.button_link||'/catalog'} aria-label={current.title}>
 {current.image_url?<img src={current.image_url} alt={current.title} className="carousel-banner-img"/>:<div className="carousel-text-slide"><span>{current.eyebrow}</span><strong>{current.title}</strong><small>{current.subtitle}</small></div>}</Link>
 {banners.length>1&&<><button type="button" className="carousel-control previous" onClick={()=>change(-1)} aria-label="Попередній банер"><ArrowLeft size={16}/></button><button type="button" className="carousel-control next" onClick={()=>change(1)} aria-label="Наступний банер"><ArrowRight size={16}/></button><div className="carousel-dots" aria-label="Слайди">{banners.map((b,i)=><button key={b.id} type="button" className={active===i?'current':''} onClick={()=>setActive(i)} aria-label={`Банер ${i+1}`}/>)}</div></>}
 </section>;
}
function Home(){
 const banners=useFetch<Banner[]>('/banners'),categories=useFetch<Category[]>('/categories'),brands=useFetch<Brand[]>('/brands'),products=useFetch<Product[]>('/products'),{me,bonusPercent}=useStore();
 const slides=(banners.data||[]).filter(b=>b.kind==='hero'),bonus=banners.data?.find(b=>b.kind==='bonus');
 const primary=PRIMARY_CATEGORY_SLUGS.map(slug=>(categories.data||[]).find(c=>c.slug===slug)).filter((c):c is Category=>Boolean(c));
 return <div className="home-page updated-home">
 <HeroCarousel banners={slides}/>
 <div className="trust-strip"><div><ShieldCheck size={18}/> Оригінальна<br/>продукція</div><div><Zap size={18}/> Швидке<br/>оформлення</div><div><Truck size={18}/> Доставка<br/>по Україні</div></div>
 <div className="section-heading"><div><span className="tiny-label">SHOP BY CATEGORY</span><h2>Категорії <em>товарів</em></h2></div><Link to="/catalog">Усі <ArrowRight size={16}/></Link></div>
 <div className="category-tiles three-main">{primary.map((c,i)=><Link to={`/catalog/${c.slug}`} className={`category-tile tile-${i} category-photo-tile`} key={c.id}>{c.image_url&&<div className="tile-photo" style={{backgroundImage:`linear-gradient(180deg,rgba(7,10,21,.1),rgba(7,10,21,.85)),url(${c.image_url})`}}/>}<div className="tile-icon">{i===0?<Zap/>:i===1?<Box/>:<Package/>}</div><b>{c.name}</b><ChevronRight size={16}/></Link>)}</div>
 <Link to={bonus?.button_link||'/bonuses'} className="bonus-banner">{bonus?.image_url&&<div className="banner-image-bg" style={{backgroundImage:`url(${bonus.image_url})`}}/>}<div className="bonus-orb"><Crown size={33}/></div><div><span>VAPORIA <b>CLUB</b> <Sparkles size={11}/></span><h3>{bonus?.title||'ТВОЇ ПОКУПКИ — ТВОЇ БОНУСИ'}</h3><p>{bonus?.subtitle||`Повертаємо ${bonusPercent}% бонусами`}</p><div className="bonus-link">ДЕТАЛЬНІШЕ <ArrowRight size={14}/></div></div></Link>
 <div className="section-heading"><div><span className="tiny-label">OUR BRANDS</span><h2>Наші <em>виробники</em></h2></div></div>
 {brands.loading?<Loading/>:<div className="brand-grid">{(brands.data||[]).map(b=><Link key={b.id} to={`/brand/${b.slug}`} className="brand-tile">{b.image_url?<img src={b.image_url} alt={b.name} loading="lazy"/>:<span className="brand-monogram">{b.name.split(' ').map(x=>x[0]).join('').slice(0,3)}</span>}<strong>{b.name}</strong><ChevronRight size={14}/></Link>)}</div>}
 <div className="section-heading"><div><span className="tiny-label">OUR FAVORITES</span><h2>Популярні <em>товари</em></h2></div><Link to="/catalog">Дивитись усі <ArrowRight size={16}/></Link></div>
 {products.loading?<Loading/>:<div className="product-grid">{(products.data||[]).slice(0,6).map(p=><ProductCard product={p} key={p.id}/>)}</div>}
 <div className="small-promo"><span><Gift size={24}/></span><div><b>Бонуси вже чекають!</b><p>{me?.bonus_balance||0} бонусів на вашому рахунку</p></div><Link to="/profile"><ArrowRight size={18}/></Link></div><div className="age-note">18+ • Інформація лише для повнолітніх. Дотримуйтеся місцевого законодавства.</div>
 </div>;
}
function Catalog(){const {data,loading}=useFetch<Category[]>('/categories');const visible=PRIMARY_CATEGORY_SLUGS.map(slug=>data?.find(c=>c.slug===slug)).filter((c):c is Category=>Boolean(c));return <div><PageTitle subtitle="Вибирайте свій напрям">Каталог</PageTitle>{loading?<Loading/>:<div className="catalog-list">{visible.map((c,i)=><Link to={`/catalog/${c.slug}`} className={`catalog-row catalog-${i%5}`} key={c.id}>{c.image_url&&<div className="catalog-image-bg" style={{backgroundImage:`url(${c.image_url})`}}/>}<div className="catalog-icon">{i===0?<Zap size={25}/>:i===1?<Box size={25}/>:i===2?<Package size={25}/>:i===3?<Star size={25}/>:<Crown size={25}/>}</div><div><b>{c.name}</b><span>{c.subtitle}</span></div><div className="catalog-arrow"><ChevronRight size={19}/></div></Link>)}</div>}</div>;}
function CategoryPage(){const {slug}=useParams(),{data,loading}=useFetch<Product[]>(`/products?category=${encodeURIComponent(slug||'')}`);const cats=useFetch<Category[]>('/categories');const category=cats.data?.find(c=>c.slug===slug);return <div><PageTitle subtitle={`${data?.length||0} товарів`}>{category?.name||'Товари'}</PageTitle>{loading?<Loading/>:data?.length?<div className="product-grid">{data.map(p=><ProductCard product={p} key={p.id}/>)}</div>:<Empty title="Наразі тут порожньо" link="/catalog"/>}</div>;}
function BrandPage(){const {slug}=useParams(),{data:brands}=useFetch<Brand[]>('/brands'),{data:products,loading}=useFetch<Product[]>(`/products?brand=${encodeURIComponent((brands?.find(b=>b.slug===slug)?.name)||'')}`);
 const current=brands?.find(b=>b.slug===slug);if(!brands)return <Loading/>;if(!current)return <Empty title="Виробника не знайдено" link="/" linkText="На головну"/>;return <div><PageTitle subtitle="Товари виробника">{current?.name||'Виробник'}</PageTitle>
 {current?.image_url&&<div className="brand-detail-hero"><img src={current.image_url} alt={current.name}/></div>}
 {loading?<Loading/>:products?.length?<div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<Empty icon={Package} title="Поки немає товарів цього виробника" subtitle="Додайте товари з цією назвою бренду в адмінпанелі" link="/" linkText="На головну"/>}</div>;}
function ProductPage(){const {slug}=useParams(),{data:p,loading}=useFetch<Product>(`/products/${slug}`);const {notify,refreshCart}=useStore();const [variant,setVariant]=useState<number|null>(null),[qty,setQty]=useState(1),[selectedPhoto,setSelectedPhoto]=useState(''),[adding,setAdding]=useState(false),[fav,setFav]=useState(false);const navigate=useNavigate();
 useEffect(()=>{if(p){setVariant(p.variants[0]?.id||null);setSelectedPhoto(p.image_url||'');setQty(1);}},[p?.id]);
 const selected=p?.variants.find(v=>v.id===variant);const unit=selected?.price_override ?? p?.base_price ?? 0;const related=useFetch<Product[]>(`/products?category=${encodeURIComponent(p?.category_slug||'')}`);
 const add=async()=>{if(!selected)return;setAdding(true);try{await api('/cart',json('POST',{variant_id:selected.id,quantity:qty}));await refreshCart();notify('Товар додано до кошика');window.Telegram?.WebApp?.HapticFeedback?.impactOccurred('light');}catch(e){notifyError(e,notify);}finally{setAdding(false);}};
 const toggle=async()=>{if(!p)return;try{const r=await api<{favorite:boolean}>(`/me/favorites/${p.id}`,json('POST'));setFav(r.favorite);notify(r.favorite?'Додано в обране':'Прибрано з обраного');}catch(e){notifyError(e,notify);}};
 return <div className="product-page">{loading?<Loading/>:!p?<Empty title="Товар не знайдено" link="/catalog"/>:<>
 <div className="product-gallery"><div className="gallery-actions"><button onClick={()=>navigate(-1)}><ArrowLeft size={20}/></button><div><button aria-label="В обране" onClick={toggle}><Heart size={21} fill={fav?'currentColor':'none'}/></button><button aria-label="Поділитися" onClick={()=>{void navigator.clipboard?.writeText(location.href);notify('Посилання скопійовано');}}><UploadCloud size={20}/></button></div></div><Art product={{...p,image_url:selectedPhoto}} size="big"/>{p.badge&&<span className="gallery-badge">{p.badge}</span>}</div>
 <div className="photo-thumbs">{[p.image_url,...(p.gallery||[])].filter(Boolean).length?[p.image_url,...p.gallery].filter(Boolean).map((photo,i)=><button key={i} className={selectedPhoto===photo?'selected':''} onClick={()=>setSelectedPhoto(photo)}><img src={photo} alt={`Фото ${i+1}`}/></button>):<><div className="fake-thumb selected"><Zap size={20}/></div><div className="fake-thumb"><Crown size={20}/></div><div className="fake-thumb"><Sparkles size={20}/></div></>}</div>
 <div className="product-meta"><span className="eyebrow">{p.brand} / {p.category_name}</span><h1>{p.name}</h1><div className="rating-line"><Star size={14} fill="#ffc66b" color="#ffc66b"/><span>Варіанти на вибір</span><i/> <span>Наявність: {selected?.stock||0} шт.</span></div><div className="detail-price"><strong>{price(unit)}</strong>{p.compare_at_price&&<del>{price(p.compare_at_price)}</del>}</div></div>
 <div className="choices"><h3>Оберіть {p.category_slug==='pod-systemy'?'колір / комплектацію':'смак / варіант'}</h3><div className="variant-list">{p.variants.map(v=><button className={v.id===variant?'picked':''} disabled={!v.stock||!v.is_active} key={v.id} onClick={()=>{setVariant(v.id);setQty(1);}}>{v.label}{!v.stock&&<small>Немає</small>}</button>)}</div></div>
 <div className="qty-row"><div><b>Кількість</b><small>В наявності: {selected?.stock||0}</small></div><div className="stepper"><button disabled={qty<=1} onClick={()=>setQty(q=>Math.max(1,q-1))}><Minus size={16}/></button><strong>{qty}</strong><button disabled={qty>=(selected?.stock||0)} onClick={()=>setQty(q=>q+1)}><Plus size={16}/></button></div></div>
 <button className="button primary product-add" disabled={!selected?.stock||adding} onClick={()=>void add()}><ShoppingCart size={19}/> {adding?'ДОДАВАННЯ...':'ДОДАТИ В КОШИК'} <span>{price(unit*qty)}</span></button>
 <div className="product-description"><div className="description-title"><Sparkles size={18}/> Про товар</div><p>{p.description||p.subtitle}</p><div className="description-detail"><ShieldCheck size={18}/> Оригінальна продукція • Уточнюйте характеристики перед покупкою</div></div>
 {(related.data||[]).filter(item=>item.id!==p.id).length>0&&<><div className="section-heading related-head"><h2>Може <em>зацікавити</em></h2></div><div className="product-grid">{related.data!.filter(item=>item.id!==p.id).slice(0,4).map(item=><ProductCard key={item.id} product={item}/>)}</div></>}
 </>}</div>;
}
function SearchPage(){const [q,setQ]=useState(''),[debounced,setDebounced]=useState('');useEffect(()=>{const t=setTimeout(()=>setDebounced(q.trim()),250);return()=>clearTimeout(t);},[q]);const {data,loading}=useFetch<Product[]>(`/products?search=${encodeURIComponent(debounced)}`);const chips=['INBOTTLE','HYPE','VAPORESSO','CHASER','POD','Картриджі','Blue razz','Lemon'];return <div><PageTitle subtitle="Знайди те, що подобається">Пошук</PageTitle><div className="search-box"><SearchIcon size={21}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Товари, бренди, смаки..."/>{q&&<button onClick={()=>setQ('')}><X size={18}/></button>}</div><div className="search-suggestions"><h3>{q?'Результати пошуку':'Популярні запити'}</h3>{!q&&<div className="search-chips">{chips.map(c=><button key={c} onClick={()=>setQ(c)}>{c} <ArrowRight size={12}/></button>)}</div>}</div>{loading?<Loading/>:data?.length?<div className="product-grid search-results">{data.map(p=><ProductCard product={p} key={p.id}/>)}</div>:<Empty icon={SearchIcon} title="Нічого не знайдено" subtitle="Спробуйте іншу назву або бренд"/>}</div>;}
function CartPage(){const {notify,refreshCart,me,checkoutEnabled}=useStore();const {data,loading,reload}=useFetch<Cart>('/cart'),[promo,setPromo]=useState(sessionStorage.getItem('vaporia_promo')||''),[discount,setDiscount]=useState(0);const navigate=useNavigate();
 const change=async(id:string,quantity:number)=>{try{await api(`/cart/${id}`,json('PATCH',{quantity}));await Promise.all([reload(),refreshCart()]);}catch(e){notifyError(e,notify);}};
 const apply=async()=>{if(!promo.trim()){setDiscount(0);sessionStorage.removeItem('vaporia_promo');return;}try{const r=await api<{discount:number}>('/coupon/check',json('POST',{code:promo,subtotal:data?.subtotal||0}));setDiscount(r.discount);sessionStorage.setItem('vaporia_promo',promo.trim().toUpperCase());notify('Промокод застосовано');}catch(e){setDiscount(0);notifyError(e,notify);}};
 useEffect(()=>{setDiscount(0);},[data?.subtotal]);
 return <div><PageTitle subtitle={`${data?.items.length||0} позицій`}>Кошик</PageTitle>{loading?<Loading/>:!data?.items.length?<Empty icon={ShoppingCart} title="Тут поки порожньо" subtitle="Час знайти щось цікаве!" link="/catalog" linkText="ПЕРЕЙТИ ДО КАТАЛОГУ"/>:<><div className="cart-list">{data.items.map(item=><div className="cart-item" key={item.id}><Link to={`/product/${item.slug}`}><Art product={{name:item.name,image_url:item.image_url}}/></Link><div className="cart-item-main"><b>{item.name}</b><p>{item.variant_label}</p><strong>{price(item.unit_price*item.quantity)}</strong><div className="cart-stepper"><div className="stepper"><button onClick={()=>void change(item.id,item.quantity-1)}><Minus size={14}/></button><span>{item.quantity}</span><button disabled={item.quantity>=item.stock} onClick={()=>void change(item.id,item.quantity+1)}><Plus size={14}/></button></div><button className="trash-btn" aria-label="Видалити" onClick={()=>void change(item.id,0)}><Trash2 size={17}/></button></div></div></div>)}</div>
 <div className="panel promo-panel"><h3><Ticket size={17}/> Промокод</h3><div className="promo-input"><input placeholder="Введіть промокод" value={promo} onChange={e=>setPromo(e.target.value)} /><button onClick={()=>void apply()}><ArrowRight size={19}/></button></div></div>
 <div className="panel totals-panel"><div><span>Вартість товарів</span><b>{price(data.subtotal)}</b></div><div><span>Знижка</span><b className="accent-discount">−{price(discount)}</b></div><div><span>Ваші бонуси</span><b>{me?.bonus_balance||0} <Crown size={13}/></b></div><div className="total-final"><span>До оплати</span><strong>{price(data.subtotal-discount)}</strong></div><small>* Доставку перевізника оплачують окремо, якщо вона передбачена.</small></div>
 <button disabled={!checkoutEnabled} className="button primary full-width checkout-link" onClick={()=>navigate('/checkout')}><ShoppingBag size={20}/> {checkoutEnabled?'ОФОРМИТИ ЗАМОВЛЕННЯ':'ОФОРМЛЕННЯ ПОКИ НЕДОСТУПНЕ'} <ArrowRight size={17}/></button>{!checkoutEnabled&&<p className="checkout-warning">Оформлення тимчасово закрите, доки продавець не налаштує юридичні вимоги й перевірку повноліття.</p>}
 </>}</div>;
}
function CheckoutPage(){const {data,loading}=useFetch<Cart>('/cart'),{me,refreshMe,refreshCart,notify,checkoutEnabled}=useStore(),navigate=useNavigate();const [name,setName]=useState(''),[phone,setPhone]=useState(''),[city,setCity]=useState(''),[details,setDetails]=useState(''),[delivery,setDelivery]=useState<'nova_poshta'|'pickup'>('nova_poshta'),[payment,setPayment]=useState<'cod'|'manager'>('cod'),[comment,setComment]=useState(''),[promo,setPromo]=useState(sessionStorage.getItem('vaporia_promo')||''),[discount,setDiscount]=useState(0),[bonus,setBonus]=useState(0),[agreed,setAgreed]=useState(false),[submitting,setSubmitting]=useState(false);const requestId=useRef(crypto.randomUUID());
 useEffect(()=>{if(me?.first_name)setName(me.first_name);},[me?.first_name]);
 useEffect(()=>{if(promo&&data?.subtotal){api<{discount:number}>('/coupon/check',json('POST',{code:promo,subtotal:data.subtotal})).then(r=>setDiscount(r.discount)).catch(()=>{setPromo('');setDiscount(0);});}},[data?.subtotal]);
 const allowed=Math.min(me?.bonus_balance||0,Math.floor(Math.max(0,(data?.subtotal||0)-discount)*0.3/100));
 const finalTotal=Math.max(0,(data?.subtotal||0)-discount-bonus*100);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!data?.items.length)return;setSubmitting(true);try{const r=await api<{order:{id:string;number:string}}>('/checkout',json('POST',{request_id:requestId.current,customer_name:name,phone,delivery_method:delivery,city,shipping_details:delivery==='pickup'?'Самовивіз':details,payment_method:payment,comment,coupon_code:promo,bonus_used:bonus,age_agreed:agreed}));sessionStorage.removeItem('vaporia_promo');await Promise.all([refreshCart(),refreshMe()]);navigate(`/order-success/${r.order.number}`,{replace:true});}catch(err){notifyError(err,notify);}finally{setSubmitting(false);}};
 if(!checkoutEnabled)return <Empty icon={ShieldCheck} title="Оформлення тимчасово закрите" subtitle="Адміністратор має налаштувати правові вимоги та перевірку повноліття" link="/cart" linkText="Повернутись у кошик"/>;if(loading)return <Loading/>;if(!data?.items.length)return <Empty title="Спочатку додайте товар" link="/catalog"/>;
 return <div><PageTitle subtitle="Залишився лише один крок">Оформлення</PageTitle><form onSubmit={e=>void submit(e)} className="checkout-form"><section className="panel checkout-panel"><h3><UserRound size={20}/> Контактні дані</h3><label>Ваше ім’я<input required minLength={2} maxLength={90} value={name} onChange={e=>setName(e.target.value)} placeholder="Ім’я та прізвище"/></label><label>Номер телефону<input required type="tel" pattern="[+0-9 ()-]{9,22}" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+380XXXXXXXXX"/></label></section>
 <section className="panel checkout-panel"><h3><Truck size={20}/> Доставка</h3><div className="segmented"><button type="button" className={delivery==='nova_poshta'?'chosen':''} onClick={()=>setDelivery('nova_poshta')}>Нова пошта</button><button type="button" className={delivery==='pickup'?'chosen':''} onClick={()=>setDelivery('pickup')}>Самовивіз</button></div><label>Місто<input required value={city} onChange={e=>setCity(e.target.value)} placeholder="Назва міста" maxLength={100}/></label>{delivery==='nova_poshta'&&<label>Відділення / поштомат<input required value={details} onChange={e=>setDetails(e.target.value)} placeholder="№ відділення або адреса" maxLength={200}/></label>}</section>
 <section className="panel checkout-panel"><h3><ShoppingBag size={20}/> Оплата</h3><div className="payment-options"><label><input type="radio" checked={payment==='cod'} onChange={()=>setPayment('cod')}/> При отриманні (за домовленістю)</label><label><input type="radio" checked={payment==='manager'} onChange={()=>setPayment('manager')}/> Узгодити з менеджером</label></div><small>Онлайн-еквайринг поки не підключено. Менеджер підтвердить доступний спосіб оплати.</small></section>
 <section className="panel checkout-panel"><h3><Crown size={20}/> Бонуси та промокод</h3><div className="mini-promo"><input placeholder="Промокод" value={promo} onChange={e=>setPromo(e.target.value.toUpperCase())}/><button type="button" onClick={async()=>{try{const r=await api<{discount:number}>('/coupon/check',json('POST',{code:promo,subtotal:data.subtotal}));setDiscount(r.discount);setBonus(0);notify('Промокод діє');}catch(e){setDiscount(0);notifyError(e,notify);}}}>Застосувати</button></div><div className="bonus-checkbox"><div><b>Списати бонуси</b><small>Доступно {me?.bonus_balance||0}; максимум {allowed} бонусів (30%)</small></div><input type="number" min={0} max={allowed} value={bonus} onChange={e=>setBonus(Math.min(allowed,Math.max(0,Math.floor(Number(e.target.value)||0))))}/></div></section>
 <section className="panel checkout-panel"><label>Коментар до замовлення<textarea rows={3} maxLength={800} value={comment} onChange={e=>setComment(e.target.value)} placeholder="За бажанням"/></label></section>
 <div className="panel totals-panel"><div><span>Товари</span><b>{price(data.subtotal)}</b></div><div><span>Знижка / бонуси</span><b>−{price(discount+bonus*100)}</b></div><div className="total-final"><span>До оплати</span><strong>{price(finalTotal)}</strong></div></div>
 {me && !me.age_verified && <div className="panel admin-info">Для реального продажу адміністратор повинен перевірити документ, що підтверджує вік, та дозволити оформлення. У деморежимі перевірка може бути вимкнена.</div>}<label className="accept-check"><input type="checkbox" required checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>Підтверджую, що мені виповнилося 18 років, дані замовлення правильні та розумію, що менеджер має підтвердити доступність товарів і порядок доставки. Під час видачі може знадобитися документ.</span></label><button className="button primary full-width" type="submit" disabled={!agreed||submitting}>{submitting?'ВІДПРАВЛЯЄМО...':'ПІДТВЕРДИТИ ЗАМОВЛЕННЯ'} <ArrowRight size={17}/></button>
 </form></div>;
}
function OrderSuccess(){const {number}=useParams();return <div className="success-screen"><div className="success-icon"><Check size={45}/></div><span className="eyebrow">ORDER RECEIVED</span><h1>ДЯКУЄМО<br/><em>ЗА ЗАМОВЛЕННЯ!</em></h1><p>Замовлення №{number} отримано. Менеджер зв’яжеться з вами для підтвердження та узгодження доставки.</p><Link to="/profile" className="button primary">ІСТОРІЯ ЗАМОВЛЕНЬ <ArrowRight size={16}/></Link><Link to="/" className="button ghost">Повернутися на головну</Link></div>;}
function Favorites(){const {data,loading,reload}=useFetch<Product[]>('/me/favorites');return <div><PageTitle subtitle="Те, що вам сподобалось">Обране</PageTitle>{loading?<Loading/>:!data?.length?<Empty icon={Heart} title="Поки немає обраного" link="/catalog"/>:<div className="product-grid">{data.map(p=><ProductCard key={p.id} product={p} onChanged={()=>void reload()}/>)}</div>}</div>;}
function BonusHistory(){const {data,loading}=useFetch<{id:string;delta:number;description:string;created_at:string}[]>('/me/bonuses'),{me,bonusPercent}=useStore();return <div><PageTitle subtitle="Нарахування та списання">Мої бонуси</PageTitle><div className="bonus-balance large"><span><Crown size={21}/> VAPORIA CLUB</span><strong>{me?.bonus_balance||0} <small>БОНУСІВ</small></strong><p>{bonusPercent}% від виконаних замовлень • 1 бонус = 1 ₴ • списання до 30% суми</p></div>{loading?<Loading/>:(data||[]).length?<div className="history-list">{data!.map(r=><div className="history-row" key={r.id}><div><b>{r.description}</b><small>{new Date(r.created_at).toLocaleString('uk-UA')}</small></div><strong className={r.delta>=0?'positive':'negative'}>{r.delta>0?'+':''}{r.delta}</strong></div>)}</div>:<Empty icon={Crown} title="Історії поки немає" subtitle="За завершені замовлення нараховуються бонуси"/>}</div>;}
function Orders(){const {data,loading}=useFetch<Order[]>('/me/orders');return <div><PageTitle subtitle="Стежте за своїми покупками">Історія замовлень</PageTitle>{loading?<Loading/>:data?.length?<div className="orders-list">{data.map(o=><div className="panel order-card" key={o.id}><div className="order-head"><div><span className="eyebrow">ЗАМОВЛЕННЯ</span><h3>№{o.number}</h3></div><span className={`status status-${o.status}`}>{statusTitle[o.status]}</span></div><small>{new Date(o.created_at).toLocaleString('uk-UA')}</small><div className="order-items">{o.items.map((item,i)=><p key={i}>{item.product_name} <span>×{item.quantity}</span><br/><small>{item.variant_label}</small></p>)}</div><div className="order-foot"><span>До оплати</span><strong>{price(o.total)}</strong></div>{o.bonus_awarded>0&&<div className="order-bonus"><Crown size={14}/> Нараховано {o.bonus_awarded} бонусів</div>}</div>)}</div>:<Empty icon={ClipboardList} title="Замовлень ще немає" link="/catalog"/>}</div>;}
function Profile(){const {me,bonusPercent}=useStore();return <div><PageTitle subtitle="Ваш особистий простір">Профіль</PageTitle><div className="profile-user"><img src={me?.photo_url||'/brand-logo.png'} alt="Аватар"/><div><span>ПРИВІТ,</span><h2>{me?.first_name||'Клієнт VAPORIA'} <Sparkles size={16}/></h2><p>@{me?.username||'vaporia_member'}</p></div><Crown size={24}/></div><Link to="/bonuses" className="bonus-balance"><div className="balance-top"><span><Crown size={22}/> VAPORIA CLUB</span><ChevronRight size={18}/></div><span className="balance-caption">ВАШ БАЛАНС БОНУСІВ</span><strong>{me?.bonus_balance||0} <small>БОНУСІВ</small></strong><p>Отримуйте {bonusPercent}% після виконаного замовлення</p><div className="balance-spark">✦</div></Link><div className="profile-menu"><Link to="/orders"><span className="profile-icon"><ClipboardList size={20}/></span><span>Історія замовлень<small>Ваші замовлення та їхній статус</small></span><ChevronRight/></Link><Link to="/favorites"><span className="profile-icon"><Heart size={20}/></span><span>Обране<small>Збережені товари</small></span><ChevronRight/></Link><Link to="/bonuses"><span className="profile-icon"><Gift size={20}/></span><span>Мої бонуси<small>Історія нарахувань і списань</small></span><ChevronRight/></Link>{me?.role==='admin'&&<Link to="/admin"><span className="profile-icon"><Settings2 size={20}/></span><span>Адмінпанель<small>Товари, замовлення, банери</small></span><ChevronRight/></Link>}</div><div className="profile-bottom"><ShieldCheck size={18}/> VAPORIA DISTRO • PREMIUM STORE • 18+</div></div>;}
async function uploadMedia(file:File):Promise<string>{
 if(!['image/jpeg','image/png','image/webp','image/heic','image/heif'].includes(file.type) && !/\.hei[cf]$/i.test(file.name))throw new Error('Виберіть фото JPG, PNG, WEBP або HEIC');
 if(file.size>16*1024*1024)throw new Error('Фото завелике (макс. 16 МБ до стиснення)');
 let body:Blob=file;
 // Resize larger smartphone photos to web-friendly dimensions before upload.
 if(file.size>3.8*1024*1024 || !['image/png','image/jpeg','image/webp'].includes(file.type)){
  const img=await createImageBitmap(file).catch(()=>{throw new Error('Цей HEIC не вдалося перетворити. Збережіть фото у JPG або PNG.');});const ratio=Math.min(1,1600/Math.max(img.width,img.height));
  const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*ratio));canvas.height=Math.max(1,Math.round(img.height*ratio));
  canvas.getContext('2d')?.drawImage(img,0,0,canvas.width,canvas.height);img.close();
  body=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error('Не вдалося підготувати фото')),'image/webp',0.82));
 }
 if(body.size>4*1024*1024)throw new Error('Фото перевищує 4 МБ. Зменште його розмір.');
 const response=await fetch('/api/admin/media',{method:'POST',headers:{'X-Vaporia-App':'1','Content-Type':body.type},credentials:'same-origin',body});
 const result=await response.json().catch(()=>({error:'Помилка завантаження'}));
 if(!response.ok)throw new Error(result.error||'Не вдалося завантажити фото');
 return String(result.url);
}
function PhotoField({name='image_url',label,initial='',notify}:{name?:string;label:string;initial?:string;notify:(message:string,type?:'ok'|'error')=>void}){
 const [url,setUrl]=useState(initial),[uploading,setUploading]=useState(false);
 return <div className="photo-admin-field"><label>{label}<input name={name} value={url} maxLength={600} onChange={e=>setUrl(e.target.value)} placeholder="Завантажте фото або вставте HTTPS URL"/></label>
 <div className="photo-input-row"><label className="photo-upload-btn"><UploadCloud size={17}/>{uploading?'Завантаження...':'Завантажити фото'}<input disabled={uploading} type="file" accept="image/png,image/jpeg,image/webp,image/heic,image/heif" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);try{const address=await uploadMedia(file);setUrl(address);notify('Фото додано до PostgreSQL');}catch(error){notifyError(error,notify);}finally{setUploading(false);e.target.value='';}}}/></label>
 {url&&<img className="photo-preview" src={url} alt="Попередній перегляд" onError={e=>{e.currentTarget.style.opacity='.3';}}/>}</div><small>JPG / PNG / WEBP до 4 МБ; фотографія зберігається у PostgreSQL. Після завантаження натисніть «Зберегти» у формі.</small></div>;
}
function GalleryPhotosField({initial='',notify}:{initial?:string;notify:(message:string,type?:'ok'|'error')=>void}){
 const [urls,setUrls]=useState(initial),[busy,setBusy]=useState(false);
 return <div className="photo-admin-field"><label>Галерея — по одному фото / URL на рядок<textarea rows={3} name="gallery" value={urls} onChange={e=>setUrls(e.target.value)}/></label>
 <label className="photo-upload-btn"><UploadCloud size={17}/>{busy?'Завантаження...':'Додати фото до галереї'}<input type="file" multiple accept="image/png,image/jpeg,image/webp,image/heic,image/heif" disabled={busy} onChange={async e=>{const files=Array.from(e.target.files||[]).slice(0,12);setBusy(true);try{for(const file of files){const address=await uploadMedia(file);setUrls(old=>old.trim()?old.trim()+'\n'+address:address);}notify(`${files.length} фото додано до галереї`);}catch(err){notifyError(err,notify);}finally{setBusy(false);e.target.value='';}}}/></label></div>;
}
function Admin(){const {notify,brand}=useStore();const [tab,setTab]=useState<'overview'|'orders'|'products'|'categories'|'brands'|'banners'|'coupons'|'bonus'>('overview'),[rev,setRev]=useState(0);const [picked,setPicked]=useState<any>(null);const [newMode,setNewMode]=useState(false);const refresh=()=>{setRev(v=>v+1);setPicked(null);setNewMode(false);};
 const [brands,setBrands]=useState<Brand[]>([]);const [overview,setOverview]=useState<any>(null),[orders,setOrders]=useState<Order[]>([]),[products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[banners,setBanners]=useState<Banner[]>([]),[coupons,setCoupons]=useState<Coupon[]>([]);
 useEffect(()=>{const doFetch=async()=>{try{const [a,b,c,d,e,f,g]=await Promise.all([api('/admin/overview'),api<Order[]>('/admin/orders'),api<Product[]>('/admin/products'),api<Category[]>('/admin/categories'),api<Banner[]>('/admin/banners'),api<Coupon[]>('/admin/coupons'),api<Brand[]>('/admin/brands')]);setBrands(g);setOverview(a);setOrders(b);setProducts(c);setCategories(d);setBanners(e);setCoupons(f);}catch(err){notifyError(err,notify);}};void doFetch();},[rev]);
 const updateStatus=async(o:Order,status:string)=>{if(!confirm(`Перевести замовлення №${o.number} у статус «${statusTitle[status]}»?`))return;try{await api(`/admin/orders/${o.id}/status`,json('PATCH',{status}));notify('Статус збережено');refresh();}catch(e){notifyError(e,notify);}};
 const saveCategory=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{const body={slug:String(d.slug),name:String(d.name),subtitle:String(d.subtitle),icon:String(d.icon),image_url:String(d.image_url),sort_order:Number(d.sort_order),is_active:d.is_active==='on'};await api(`/admin/categories${picked?.id?'/'+picked.id:''}`,json(picked?.id?'PATCH':'POST',body));notify('Категорію збережено');refresh();}catch(e){notifyError(e,notify);}};
 const saveBrand=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{const body={slug:String(d.slug),name:String(d.name),image_url:String(d.image_url),sort_order:Number(d.sort_order),is_active:d.is_active==='on'};await api(`/admin/brands${picked?.id?'/'+picked.id:''}`,json(picked?.id?'PATCH':'POST',body));notify('Виробника збережено');refresh();}catch(err){notifyError(err,notify);}};
 const saveBanner=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{const body={eyebrow:String(d.eyebrow),title:String(d.title),subtitle:String(d.subtitle),image_url:String(d.image_url),button_text:String(d.button_text),button_link:String(d.button_link),kind:String(d.kind),sort_order:Number(d.sort_order),is_active:d.is_active==='on'};await api(`/admin/banners${picked?.id?'/'+picked.id:''}`,json(picked?.id?'PATCH':'POST',body));notify('Банер збережено');refresh();}catch(e){notifyError(e,notify);}};
 const saveCoupon=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{const body={code:String(d.code),kind:String(d.kind),value:String(d.kind)==='fixed'?kop(String(d.value)):Number(d.value),min_subtotal:kop(String(d.min_subtotal)),max_uses:d.max_uses?Number(d.max_uses):null,is_active:d.is_active==='on'};await api(`/admin/coupons${picked?.id?'/'+picked.id:''}`,json(picked?.id?'PATCH':'POST',body));notify('Промокод збережено');refresh();}catch(e){notifyError(e,notify);}};
 const saveProduct=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{
   const slug=String(d.slug);const old=(picked?.variants||[]) as Variant[];
   const variantText=String(d.variants||'').split('\n').map(s=>s.trim()).filter(Boolean);
   const variants=variantText.map((line,i)=>{const [label,skuRaw,stockRaw,overrideRaw]=line.split('|').map(s=>s.trim());const sku=skuRaw||`${slug}-${i+1}`;const existing=old.find(v=>v.sku===sku);return {...(existing?.id?{id:existing.id}:{}),label,sku,stock:Math.max(0,Number(stockRaw||0)),price_override:overrideRaw?kop(overrideRaw):null,is_active:true};});
   const body={category_id:Number(d.category_id),slug,name:String(d.name),brand:String(d.brand),subtitle:String(d.subtitle),description:String(d.description),image_url:String(d.image_url),gallery:String(d.gallery||'').split('\n').map(s=>s.trim()).filter(Boolean),base_price:kop(String(d.base_price)),compare_at_price:d.compare_at_price?kop(String(d.compare_at_price)):null,badge:String(d.badge),is_active:d.is_active==='on',variants};
   await api(`/admin/products${picked?.id?'/'+picked.id:''}`,json(picked?.id?'PATCH':'POST',body));notify('Товар збережено');refresh();
 }catch(err){notifyError(err,notify);}};
 const start=(item:any=null)=>{setPicked(item);setNewMode(!item);window.scrollTo({top:120,behavior:'smooth'});};
 const inputs=(keys:{name:string;label:string;type?:string;defaultValue?:string|number;placeholder?:string;required?:boolean}[])=>keys.map(k=>k.name==='image_url'?<PhotoField key={k.name} label={k.label} initial={String(k.defaultValue??'')} notify={notify}/>:<label key={k.name}>{k.label}<input name={k.name} type={k.type||'text'} step={k.type==='number'&&(['base_price','compare_at_price','value','min_subtotal'].includes(k.name))?'0.01':undefined} required={k.required} defaultValue={k.defaultValue??''} placeholder={k.placeholder}/></label>);
 return <div className="admin-page"><div className="admin-header"><span className="eyebrow">VAPORIA CONTROL CENTER</span><h1>Адмін<em>панель</em></h1><p>Керуйте каталогом, замовленнями та бонусами</p></div>
 <div className="admin-tabs">{([{id:'overview',label:'Огляд'},{id:'orders',label:'Замовлення'},{id:'products',label:'Товари'},{id:'categories',label:'Категорії'},{id:'brands',label:'Виробники'},{id:'banners',label:'Банери'},{id:'coupons',label:'Промокоди'},{id:'bonus',label:'Бонуси'}] as const).map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>{setTab(t.id);setPicked(null);setNewMode(false);}}>{t.label}</button>)}</div>
 {tab==='overview'&&<><div className="admin-stat-grid">{[{label:'Замовлень',v:overview?.orders||0,icon:ShoppingBag},{label:'Очікують',v:overview?.pending||0,icon:Clock3},{label:'Товарів',v:overview?.products||0,icon:Package},{label:'Клієнтів',v:overview?.customers||0,icon:UserRound}].map(s=><div key={s.label} className="admin-stat"><s.icon size={20}/><strong>{s.v}</strong><span>{s.label}</span></div>)}</div><div className="panel admin-info"><h3>Виконані замовлення</h3><div className="admin-revenue">{price(overview?.revenue||0)}</div><p>Сума замовлень у статусі «Виконано» (не банківська звітність).</p></div><div className="admin-info panel"><b>Важливо</b><p>Демонстраційні товари мають тестові залишки. Перед запуском перевірте ціни, склад, фото, описи, реквізити та умови продажу. Нові замовлення спершу отримують статус «Очікує».</p></div></>}
 {tab==='orders'&&<div className="admin-orders"><h2>Замовлення <span>{orders.length}</span></h2>{orders.map(o=><div className="panel admin-order" key={o.id}><div className="order-head"><h3>№{o.number}</h3><span className={`status status-${o.status}`}>{statusTitle[o.status]}</span></div><div className="admin-order-meta"><div><b>{o.customer_name}</b><a href={`tel:${o.phone}`}>{o.phone}</a></div><strong>{price(o.total)}</strong></div><p>@{o.username||o.telegram_id} · {new Date(o.created_at).toLocaleString('uk-UA')}</p><p>{o.delivery_method==='pickup'?'Самовивіз':'Нова пошта'}: {o.city}, {o.shipping_details}</p><p>Оплата: {o.payment_method==='cod'?'При отриманні':'Узгодити з менеджером'}</p>{o.comment&&<p>Коментар: {o.comment}</p>}<div className="admin-lineitems">{o.items.map((i,index)=><div key={index}>{i.product_name} / {i.variant_label} ×{i.quantity}</div>)}</div>{o.status!=='completed'&&o.status!=='cancelled'&&<div className="status-actions">{(o.status==='pending'?['confirmed','cancelled']:o.status==='confirmed'?['shipped','completed','cancelled']:['completed','cancelled']).map(s=><button key={s} onClick={()=>void updateStatus(o,s)} className={s==='cancelled'?'danger':''}>{statusTitle[s]}</button>)}</div>}</div>)}{!orders.length&&<Empty title="Замовлень поки немає"/>}</div>}
 {tab==='products'&&<><div className="admin-list-header"><h2>Товари ({products.length})</h2><button className="button secondary" onClick={()=>start()}>+ Додати</button></div>{(picked||newMode)&&<form key={picked?.id||'new-product'} onSubmit={e=>void saveProduct(e)} className="panel admin-form"><h3>{picked?.id?'Редагувати товар':'Новий товар'}</h3><label>Категорія<select name="category_id" defaultValue={picked?.category_id||categories[0]?.id}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{inputs([{name:'name',label:'Назва *',defaultValue:picked?.name,required:true},{name:'slug',label:'Slug (латиниця через дефіс) *',defaultValue:picked?.slug,required:true},{name:'brand',label:'Бренд',defaultValue:picked?.brand},{name:'subtitle',label:'Короткий підзаголовок',defaultValue:picked?.subtitle},{name:'base_price',label:'Ціна, ₴',type:'number',defaultValue:moneyInput(picked?.base_price||0),required:true},{name:'compare_at_price',label:'Стара ціна, ₴',type:'number',defaultValue:picked?.compare_at_price?moneyInput(picked.compare_at_price):''},{name:'badge',label:'Позначка (ХІТ, АКЦІЯ)',defaultValue:picked?.badge},{name:'image_url',label:'Фото HTTPS URL',defaultValue:picked?.image_url}])}<label>Опис<textarea rows={4} name="description" defaultValue={picked?.description||''}/></label><GalleryPhotosField key={picked?.id||'new-gallery'} initial={(picked?.gallery||[]).join('\n')} notify={notify}/><label>Варіанти: назва | SKU | залишок | ціна ₴ (необов'язково)<textarea rows={5} required name="variants" defaultValue={(picked?.variants||[]).filter((v:Variant)=>v.is_active).map((v:Variant)=>`${v.label} | ${v.sku} | ${v.stock} | ${v.price_override?moneyInput(v.price_override):''}`).join('\n')} placeholder={'Lemon Lime | inbottle-lemon | 20 |\nCherry | inbottle-cherry | 15 | 355'}/></label><label className="checkbox-label"><input type="checkbox" name="is_active" defaultChecked={picked?.is_active??true}/> Активний товар</label><div className="form-actions"><button className="button primary" type="submit">Зберегти</button><button className="button secondary" type="button" onClick={()=>{setPicked(null);setNewMode(false);}}>Скасувати</button></div></form>}
 <div className="admin-records">{products.map(p=><button className={`admin-record ${picked?.id===p.id?'selected':''}`} key={p.id} onClick={()=>start(p)}><Art product={p}/><span><b>{p.name}</b><small>{price(p.base_price)} • {p.variants.reduce((sum,v)=>sum+v.stock,0)} шт. • {p.is_active?'Активний':'Прихований'}</small></span><ChevronRight size={16}/></button>)}</div></>}
 {tab==='categories'&&<><div className="admin-list-header"><h2>Категорії</h2><button className="button secondary" onClick={()=>start()}>+ Додати</button></div>{(picked||newMode)&&<form key={picked?.id||'new-cat'} onSubmit={e=>void saveCategory(e)} className="panel admin-form">{inputs([{name:'name',label:'Назва',required:true,defaultValue:picked?.name},{name:'slug',label:'Slug',required:true,defaultValue:picked?.slug},{name:'subtitle',label:'Підзаголовок',defaultValue:picked?.subtitle},{name:'icon',label:'Іконка',defaultValue:picked?.icon||'box'},{name:'image_url',label:'Фонове фото URL',defaultValue:picked?.image_url},{name:'sort_order',label:'Порядок',type:'number',defaultValue:picked?.sort_order??0}])}<label className="checkbox-label"><input name="is_active" type="checkbox" defaultChecked={picked?.is_active??true}/> Активна</label><button className="button primary">Зберегти</button></form>}{categories.map(c=><button key={c.id} className="admin-record simple" onClick={()=>start(c)}><b>{c.name}</b><small>{c.slug} • {c.is_active?'Активна':'Прихована'}</small><ChevronRight size={16}/></button>)}</>}
 {tab==='brands'&&<><div className="admin-list-header"><h2>Виробники ({brands.length})</h2><button className="button secondary" onClick={()=>start()}>+ Додати</button></div>
 {(picked||newMode)&&<form key={picked?.id||'new-brand'} onSubmit={e=>void saveBrand(e)} className="panel admin-form"><h3>{picked?.id?'Редагувати виробника':'Новий виробник'}</h3>{inputs([{name:'name',label:'Назва виробника',required:true,defaultValue:picked?.name},{name:'slug',label:'Slug (латиниця через дефіс)',required:true,defaultValue:picked?.slug},{name:'image_url',label:'Логотип або фото виробника',defaultValue:picked?.image_url},{name:'sort_order',label:'Порядок',type:'number',defaultValue:picked?.sort_order??brands.length+1}])}<label className="checkbox-label"><input type="checkbox" name="is_active" defaultChecked={picked?.is_active??true}/> Активний</label><button className="button primary">Зберегти виробника</button></form>}
 {brands.map(b=><button key={b.id} className="admin-record simple admin-brand-row" onClick={()=>start(b)}>{b.image_url&&<img src={b.image_url} alt=""/>}<b>{b.name}</b><small>{b.slug} • {b.is_active?'Активний':'Прихований'}</small><ChevronRight size={16}/></button>)}</>}
 {tab==='banners'&&<><div className="admin-list-header"><h2>Банери</h2><button className="button secondary" onClick={()=>start()}>+ Додати</button></div>{(picked||newMode)&&<form key={picked?.id||'new-banner'} onSubmit={e=>void saveBanner(e)} className="panel admin-form">{inputs([{name:'eyebrow',label:'Мітка',defaultValue:picked?.eyebrow},{name:'title',label:'Заголовок',defaultValue:picked?.title,required:true},{name:'subtitle',label:'Опис',defaultValue:picked?.subtitle},{name:'image_url',label:'Фон URL (необов’язково)',defaultValue:picked?.image_url},{name:'button_text',label:'Текст кнопки',defaultValue:picked?.button_text||'Дивитися'},{name:'button_link',label:'Посилання (/catalog)',defaultValue:picked?.button_link||'/catalog'},{name:'sort_order',label:'Порядок',type:'number',defaultValue:picked?.sort_order||0}])}<label>Тип<select name="kind" defaultValue={picked?.kind||'promo'}><option value="hero">Головний</option><option value="bonus">Бонуси</option><option value="promo">Промо</option></select></label><label className="checkbox-label"><input type="checkbox" name="is_active" defaultChecked={picked?.is_active??true}/> Активний</label><button className="button primary">Зберегти</button></form>}{banners.map(b=><button key={b.id} className="admin-record simple" onClick={()=>start(b)}><b>{b.title}</b><small>{b.kind} • {b.is_active?'Активний':'Прихований'}</small><ChevronRight size={16}/></button>)}</>}
 {tab==='coupons'&&<><div className="admin-list-header"><h2>Промокоди</h2><button className="button secondary" onClick={()=>start()}>+ Додати</button></div>{(picked||newMode)&&<form key={picked?.id||'new-coupon'} onSubmit={e=>void saveCoupon(e)} className="panel admin-form">{inputs([{name:'code',label:'Код',defaultValue:picked?.code,required:true},{name:'value',label:'Значення (% або ₴)',type:'number',defaultValue:picked?(picked.kind==='fixed'?moneyInput(picked.value):picked.value):5,required:true},{name:'min_subtotal',label:'Мінімальна сума ₴',type:'number',defaultValue:picked?moneyInput(picked.min_subtotal):0},{name:'max_uses',label:'Ліміт використань (порожньо — без ліміту)',type:'number',defaultValue:picked?.max_uses??''}])}<label>Тип знижки<select name="kind" defaultValue={picked?.kind||'percent'}><option value="percent">Відсотки (%)</option><option value="fixed">Сума (₴)</option></select></label><label className="checkbox-label"><input type="checkbox" name="is_active" defaultChecked={picked?.is_active??true}/> Активний</label><button className="button primary">Зберегти</button></form>}{coupons.map(c=><button key={c.id} className="admin-record simple" onClick={()=>start(c)}><b>{c.code} — {c.kind==='percent'?c.value+'%':price(c.value)}</b><small>{c.uses} використань • {c.is_active?'Активний':'Вимкнений'}</small><ChevronRight size={16}/></button>)}</>}
 {tab==='bonus'&&<><h2>Перевірка віку клієнта</h2><div className="panel admin-info"><p>Підтверджуйте вік лише після перевірки документа або уповноваженим провайдером. Це ручний запис факту перевірки, а не автоматична ідентифікація.</p></div><form className="panel admin-form" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));void api('/admin/age/verify',json('POST',{telegram_id:d.telegram_id,verified:d.verified==='true'})).then(()=>{notify('Статус перевірки віку оновлено');(e.target as HTMLFormElement).reset();}).catch(err=>notifyError(err,notify));}}><label>Telegram ID клієнта<input required name="telegram_id" pattern="[0-9]+" placeholder="123456789"/></label><label>Рішення<select name="verified" defaultValue="true"><option value="true">Вік перевірено</option><option value="false">Зняти підтвердження</option></select></label><button className="button primary">Зберегти статус</button></form><h2>Ручне коригування бонусів</h2><div className="panel admin-info"><p>Потрібен числовий Telegram ID клієнта. Зміни записуються в історію бонусів. Введіть від’ємне число, щоб списати.</p></div><form className="panel admin-form" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));void api('/admin/bonuses/adjust',json('POST',{telegram_id:d.telegram_id,delta:Number(d.delta),description:d.description})).then(()=>{notify('Бонуси змінено');(e.target as HTMLFormElement).reset();}).catch(err=>notifyError(err,notify));}}>{inputs([{name:'telegram_id',label:'Telegram ID клієнта',required:true},{name:'delta',label:'Зміна бонусів (+/-)',type:'number',required:true},{name:'description',label:'Причина',required:true}])}<button className="button primary">Підтвердити зміну</button></form></>}
 </div>;
}
function AgeGate({brand,onConfirm}:{brand:string;onConfirm:()=>Promise<void>}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <div className="age-overlay"><div className="age-dialog"><img src="/brand-logo.png" alt="Логотип"/><span className="age-badge">18+</span><span className="eyebrow">AGE VERIFICATION</span><h1>ДОСТУП ТІЛЬКИ<br/><em>ДЛЯ ПОВНОЛІТНІХ</em></h1><p>У магазині {brand} представлені товари з віковими обмеженнями. Для продовження підтвердьте, що вам виповнилося 18 років.</p>{error&&<div className="form-error">{error}</div>}<button disabled={busy} className="button primary full-width" onClick={()=>{setBusy(true);void onConfirm().catch(e=>setError((e as Error).message)).finally(()=>setBusy(false));}}>МЕНІ Є 18 РОКІВ <Check size={17}/></button><button className="button ghost full-width" onClick={()=>window.Telegram?.WebApp?.close()}>Покинути магазин</button><small>Самодекларація не замінює перевірку віку під час продажу або видачі.</small></div></div>;}
function App(){const [me,setMe]=useState<Me|null>(null),[brand,setBrand]=useState('VAPORIA DISTRO'),[bonusPercent,setPercent]=useState(5),[checkoutEnabled,setCheckoutEnabled]=useState(false),[cartCount,setCartCount]=useState(0),[ready,setReady]=useState(false),[authError,setAuthError]=useState(''),[toast,setToast]=useState<{msg:string;type:'error'|'ok'}|null>(null);
 const toastTimeout=useRef<number>();const notify=useCallback((msg:string,type:'error'|'ok'='ok')=>{setToast({msg,type});clearTimeout(toastTimeout.current);toastTimeout.current=window.setTimeout(()=>setToast(null),3300);},[]);
 const refreshMe=useCallback(async()=>{const u=await api<Me>('/me');setMe(u);},[]);
 const refreshCart=useCallback(async()=>{try{const cart=await api<Cart>('/cart');setCartCount(cart.items.reduce((s,i)=>s+i.quantity,0));}catch{setCartCount(0);}},[]);
 useEffect(()=>{const init=async()=>{try{
  const tg=window.Telegram?.WebApp;
  tg?.ready();tg?.expand();try{tg?.setHeaderColor?.('#080c17');}catch{}
  const settings=await api<{brand:string;bonusPercent:number;devAuth:boolean;checkoutEnabled:boolean}>('/config');setBrand(settings.brand);setPercent(settings.bonusPercent);setCheckoutEnabled(settings.checkoutEnabled);
  // Existing cookie is valid if /me succeeds. Telegram auth happens only when needed.
  try{await refreshMe();}catch{
    if(tg?.initData){await api('/auth/telegram',json('POST',{initData:tg.initData}));await refreshMe();}
    else if(settings.devAuth){await api('/auth/dev',json('POST',{}));await refreshMe();}
    else throw new Error('Відкрийте цей магазин через кнопку бота в Telegram.');
  }
  await refreshCart();
 }catch(e){setAuthError((e as Error).message);}finally{setReady(true);}};void init();},[refreshCart,refreshMe]);
 if(!ready)return <div className="startup"><div className="spin"/><h2>VAPORIA <span>DISTRO</span></h2><p>Готуємо магазин...</p></div>;
 if(authError)return <div className="startup"><img src="/brand-logo.png" alt="Логотип"/><h2>VAPORIA DISTRO</h2><p>{authError}</p><button className="button secondary" onClick={()=>location.reload()}>Спробувати ще раз</button></div>;
 const confirmAge=async()=>{await api('/me/confirm-age',json('POST',{}));await refreshMe();};
 return <UserContext.Provider value={{me,brand,bonusPercent,checkoutEnabled,refreshMe,cartCount,refreshCart,notify}}><Shell><Routes><Route path="/" element={<Home/>}/><Route path="/catalog" element={<Catalog/>}/><Route path="/catalog/:slug" element={<CategoryPage/>}/><Route path="/brand/:slug" element={<BrandPage/>}/><Route path="/product/:slug" element={<ProductPage/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/cart" element={<CartPage/>}/><Route path="/checkout" element={<CheckoutPage/>}/><Route path="/order-success/:number" element={<OrderSuccess/>}/><Route path="/profile" element={<Profile/>}/><Route path="/favorites" element={<Favorites/>}/><Route path="/orders" element={<Orders/>}/><Route path="/bonuses" element={<BonusHistory/>}/><Route path="/admin" element={me?.role==='admin'?<Admin/>:<Empty icon={ShieldCheck} title="Немає доступу" link="/"/>}/><Route path="*" element={<Empty title="Сторінку не знайдено" link="/"/>}/></Routes></Shell>{me&&!me.age_confirmed&&<AgeGate brand={brand} onConfirm={confirmAge}/>} {toast&&<div className={`toast ${toast.type}`}><span>{toast.type==='error'?<CircleHelp size={18}/>:<Check size={18}/>}</span>{toast.msg}</div>}</UserContext.Provider>;
}
export default App;
